version: "3.8"

services:
  backend:
    build: ./Server Side
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: Qwerty@123
      DB_NAME: employeems
      PORT: 3000
    depends_on:
      - db
    volumes:
      - ./Server Side:/app
    restart: unless-stopped

  frontend:
    build: ./Front-End Folder
    ports:
      - "5173:5173"
    volumes:
      - ./Front-End Folder:/app
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Qwerty@123
      MYSQL_DATABASE: employeems
    volumes:
      - dbdata:/var/lib/mysql
      - ./employeems_dump.sql:/docker-entrypoint-initdb.d/employeems_dump.sql
    restart: unless-stopped

volumes:
  dbdata:
