version: "3.8"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Qwerty@123
      MYSQL_DATABASE: employeems
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build:
      context: ./Server Side
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: Qwerty@123
      DB_NAME: employeems
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build:
      context: ./front-end
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "8888:80"
    volumes:
      - ./front-end/nginx/react-app.conf:/etc/nginx/conf.d/default.conf
      - ./front-end/dist:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend

volumes:
  mysql-data:
