version: "3.8"

services:
  backend:
    build:
      context: ./Server Side
    environment:
      DB_HOST: 192.168.20.126 # Host machine IP
      DB_USER: root
      DB_PASS: Qwerty@123
      DB_NAME: employeems
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./front-end
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "8888:80"
    volumes:
      - ./front-end/nginx/react-app.conf:/etc/nginx/conf.d/default.conf
      - ./front-end/dist:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
